server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: central-logging
          uri: lb://central-logging
          predicates:
            - Path=/logs/**
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework: DEBUG
