server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: central-logging
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      database: "central-logging"
      port: 27017
      host: "localhost"
