version: '3.1'

services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - database