server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      database: "central-logging"
      port: 27017
      host: "localhost"